import { Item } from '../interfaces/item';

export const ITEMS: Item[] = [
  {
    id: 1,
    rrp: 129.99,
    brand: 'Burberry',
    name: 'Flowy Dress with pink and gold',
    size: 4,
    rentalPrice: 12.0,
    image: 'Image-Master-1.png',
  },
  {
    id: 2,
    rrp: 129.99,
    brand: 'Prada',
    name: 'Beach dress',
    size: 8,
    rentalPrice: 12.0,
    image: 'Image-Master-2.png',
  },
  {
    id: 1,
    rrp: 129.99,
    brand: 'Bhandage',
    name: 'Red dress for evening wear',
    size: 12,
    rentalPrice: 12.0,
    image: 'Image-Master-3.png',
  },
  {
    id: 1,
    rrp: 129.99,
    brand: 'Prada',
    name: 'Wedding guest',
    size: 12,
    rentalPrice: 12.0,
    image: 'Image-Master-4.png',
  },
  {
    id: 1,
    rrp: 129.99,
    brand: 'Anell',
    name: 'Nightwear',
    size: 14,
    rentalPrice: 12.0,
    image: 'Image-Master-5.png',
  },
  {
    id: 1,
    rrp: 129.99,
    brand: 'Desacada',
    name: 'Summer dress',
    size: 8,
    rentalPrice: 12.0,
    image: 'Image-Master-6.png',
  },
];
